namespace MegSWSApplication.Models.IndusRegModels
{
    public class IndustryDetails
    {
        public string UserID { get; set; }
        public string IPAddress { get; set; }
        public string CompanyName { get; set; }
        public string CompanyPAN { get; set; }
        public string CompnyRegDt { get; set; }
        public string CompnyType { get; set; }
        public string CompnyProposal { get; set; }
        public string UdyamorIEMNo { get; set; }
        public string GSTNo { get; set; }
        public string AuthReprName { get; set; }
        public string AuthReprMobile { get; set; }
        public string AuthReprEmail { get; set; }
        public string AuthReprLocality { get; set; }
        public string AuthReprDist { get; set; }
        public string AuthReprDistID { get; set; }
        public string AuthReprTaluka { get; set; }
        public string AuthReprTalukaID { get; set; }
        public string AuthReprVillage { get; set; }
        public string AuthReprVillageID { get; set; }
        public string AuthReprPincode { get; set; }
        public string LandType { get; set; }
        public string PropLocDoorno { get; set; }
        public string PropLocLocality { get; set; }
        public string PropLocDist { get; set; }
        public string PropLocDistID { get; set; }
        public string PropLocTaluka { get; set; }
        public string PropLocTalukaID { get; set; }
        public string PropLocVillage { get; set; }
        public string PropLocVillageID { get; set; }
        public string PropLocPincode { get; set; }
        public string NatureofActivity { get; set; }
        public string ManfActivity { get; set; }
        public string Manfproduct { get; set; }
        public string ServiceActivity { get; set; }
        public string ServiceTobeProviding { get; set; }
        public string ProductionNO { get; set; }
        public string ServiceNo { get; set; }
        public string DCPorOperation { get; set; }
        public string AnnualCapacity { get; set; }
        public string EstimatedProjCost { get; set; }
        public string LandAreainSqft { get; set; }
        public string CivilConstr { get; set; }
        public string PlantnMachineryCost { get; set; }
        public string Rawmaterial { get; set; }
        public string BuildingAreaSqm { get; set; }
        public string WaterReqKLD { get; set; }
        public string PowerReqKV { get; set; }
        public string WasteDetails { get; set; }
        public string HazWasteDetails { get; set; }
        public string CapitalInvestment { get; set; }
        public string FixedAssets { get; set; }
        public string MeasurementUnits { get; set; }
        public string LandValue { get; set; }
        public string BuildingValue { get; set; }
        public string WaterValue { get; set; }
        public string ElectricityValue { get; set; }
        public string WorkingCapital { get; set; }
        public string CapitalSubsidy { get; set; }
        public string PromoterEquity { get; set; }
        public string LoanAmount { get; set; }
        public string EquityAmount { get; set; }
        public string UnsecuredLoan { get; set; }
        public string InternalResources { get; set; }
        public string CetralSchemeAmount { get; set; }
        public string UnnatiSchemeAmount { get; set; }
        public string StateSchemeAmount { get; set; }
        public string DoorNo { get; set; }
        public string RegistrationNo { get; set; }
        public string RegistrationType { get; set; }
        public string Year1Value { get; set; }
        public string Year2Value { get; set; }
        public string Year3Value { get; set; }
        public string Year4Value { get; set; }
        public string Year5Value { get; set; }
        public string RevProjID { get; set; }

        public string Filepath { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileDescription { get; set; }
        public string UnitID { get; set; }
        public string Deptid { get; set; }
        public string ApprovalId { get; set; }
        public string SectorName { get; set; }
        public string Lineofacitivityid { get; set; }
        public string Category { get; set; }
        public string QueryID { get; set; }
        public string QueryResponse { get; set; }
        public string ResponseFileBy { get; set; }
        public string EligibleFlag { get; set; }
        public string InvestorId { get; set; }
        public string REP_STATEID { get; set; }
        public string REP_DISTRICNAME { get; set; }
        public string REP_MANDALNAME { get; set; }
        public string REP_VILLAGENAME { get; set; }
    }
}
